<a href="https://colab.research.google.com/github/ashutosh12mar/Foreign-Key-Web/blob/main/Numpy_Array_Creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [20]:
a=np.array([1,2,3,4,5])
print(a)
# a///=
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**Create an array using tuple**

In [13]:
a = np.array((1, 2, 3, 4, 5))
print(a)

[1 2 3 4 5]


**Double-click (or enter) to edit**

Create an array using set

In [14]:
a = np.array({1,2,3,4,5})
print(a)

{1, 2, 3, 4, 5}



Double-click (or enter) to edit


Create an array using dictionary

In [15]:
a = np.array({"one":1,"two":2,"three":3,"four":4,"five":5})
print(a)

{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}


Double-click (or enter) to edit

Create an array using range

In [16]:
a = np.array(range(1,6))
print(a)

[1 2 3 4 5]


Double-click(or enter)to edit

In [21]:
for i in range(1,6,1):
  print(i,end=' ,')


1 ,2 ,3 ,4 ,5 ,

Create an array using ones

In [22]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


Double-click(or enter)to edit

Create an array using arange

In [23]:
a = np.arange(5)
print(a)
a = np.arange(1,6)
print(a)
a = np.arange(1,6,2)
print(a)
a = np.arange(5,0,-1)
print(a)

[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


Create an array using random

In [27]:
a=np.random.rand(1,8)
print(a)
a=np.random.power(5,5)
print(a)
a=np.random.randint(5,size=5)
print(a)
rng = np.random.default_rng()
a =rng.integers(5,size=5)
print(a)

[[0.64862309 0.43679699 0.02381715 0.35308093 0.72872936 0.95443757
  0.34895569 0.28075936]]
[0.96485466 0.67568068 0.75571839 0.80254711 0.96412562]
[0 1 2 3 1]
[3 4 3 0 2]
